# Generated by Django 3.1.7 on 2021-04-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=90)),
                ('tanggal', models.CharField(max_length=35)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
    ]
