# Generated by Django 3.1.7 on 2021-04-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('K3Lh_website', '0003_jabatan_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='K3Lh_website.jabatan'),
        ),
    ]
