# Generated by Django 3.1.7 on 2021-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('K3Lh_website', '0004_pengguna_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='NIK',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='nomor',
            field=models.IntegerField(null=True),
        ),
    ]
