# Generated by Django 3.1.7 on 2021-04-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('K3Lh_website', '0005_auto_20210421_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='NIK',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='nomor',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
