# Generated by Django 3.1.7 on 2021-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('K3Lh_website', '0006_auto_20210421_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='image',
            field=models.ImageField(default='Gambarprofil.jpg', upload_to='profile_pics'),
        ),
    ]
