# Generated by Django 3.1.7 on 2021-04-25 06:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('K3Lh_website', '0007_pengguna_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pengguna',
            new_name='Profile',
        ),
    ]
