# Generated by Django 3.1.7 on 2021-04-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('K3Lh_website', '0008_auto_20210425_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kotak',
            new_name='Pendataan',
        ),
        migrations.RenameField(
            model_name='keadaan',
            old_name='jenis',
            new_name='jenis_keadaan',
        ),
    ]
